### ISSUE TITLE
[Feature Request] Allow only numbers

### ISSUE THREAD

**Issue by jericopulvera** [limichange/vue-pay-password#1]

**Comment by limichange** [comment]
👌

**Comment by limichange** [comment]
https://codesandbox.io/s/j4lwnr1rk3

I just publish v0.0.4. But I'm not testing all browser yet.

**Comment by limichange** [comment]
A new prop, onlyNumber.  The default value is true, so you just upgrade it.
https://github.com/limichange/vue-pay-password#prop

**Comment by limichange** [comment]
I closed this issue 😗

**Comment by jericopulvera** [comment]
@limichange can you update the npm package? thank you!

**Comment by limichange** [comment]
🤔 I have updatd.
![image](https://user-images.githubusercontent.com/1947344/43182121-b90e2af4-9012-11e8-9611-76774be8d774.png)
https://www.npmjs.com/package/vue-pay-password
